In [1]:
import numpy as np
a = np.array([1,2,3])

In [2]:
a

array([1, 2, 3])

In [3]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)

In [4]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
b = np.array([(1.5,2,3), (4,5,6)])

In [6]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
d = np.arange(10,25,5)

In [10]:
d

array([10, 15, 20])

In [11]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
a.shape

(3,)

In [14]:
len(a)

3

In [15]:
b.ndim

2

In [16]:
g=a-b

In [17]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [18]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [19]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [20]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [21]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [22]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])